# This is a basic workflow to help you get started with Actions

name: Push to ECR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - env:
          ACCESS_KEY_ID: ${{secrets.ACCESS_KEY_ID}}
          ACCOUNT_ID: ${{secrets.ACCOUNT_ID}}
          SECRET_ACCESS_KEY: ${{secrets.SECRET_ACCESS_KEY}}
      - uses: actions/checkout@v2
      - uses: kciter/aws-ecr-action@master
        with:
          access_key_id: $ACCESS_KEY_ID
          secret_access_key: $SECRET_ACCESS_KEY
          account_id: $ACCOUNT_ID
          repo: actions_demo
          dockerfile: Dockerfile
          region: eu-west-1
          tags: latest,${{ github.sha }}
          create_repo: true
